# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fr

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: HomemadeEntityExtractor.TestExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: SklearnIntentClassifier

#export PYTHONPATH=/path_to_your_project_dir/:$PYTHONPATH

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
  - name: KerasPolicy
    max_history: 3
    epochs: 200 
  - name: FormPolicy
  - name: MappingPolicy
  - name: TEDPolicy
    max_history: 3
    epochs: 200