# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
  - name: DucklingHTTPExtractor
    url: "http://localhost:8000"
    locale: "fr_FR"
    timezone: "Europe/Paris"
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
#export PYTHONPATH=/path_to_your_project_dir/:$PYTHONPATH

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
  - name: "KerasPolicy"
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer